import time
import sys
sys.path.append('..mise_en_place')

def reveDuPasse():
    print("La voix vous revient en mémoire.")
    time.sleep(2)
    print("Un fond blanc vous aveugle, mais vous sentez une présence à vos côtés.")
    time.sleep(2)
    print("Vous vous sentez apaisé, en sécurité.")
    time.sleep(2)
    print("Vous essayez de vous tournez vers cette présence, mais la seule chose que vous remarquez sont son sourire et une longue chevelure blondes.")
    time.sleep(2)
    print("Une voix vous réveille.")
    time.sleep(2)
    print("Hoo ! Hey ! Vous allez bien ?")
    time.sleep(2)
    print("Vous ouvrez les yeux et une jeune fille vous regarde avec inquiétude.")
    time.sleep(2)
    print("Vous vous redressez, mais vous vous sentez faible.")
    time.sleep(2)
    print("« Vous dormiez depuis ce matin. » Dit la jeune fille.")
    time.sleep(2)
    print("Vous vous frottez les yeux et regardez autour de vous. Le soleil est déjà couché.")
    time.sleep(2)
    print("Quelque chose tremblote à vos côtés.")
    time.sleep(2)
    print("« Il va bien, mais il a besoin de repos. » Répondit la jeune fille en voyant votre regard.")
    time.sleep(2)
    print("Vous vous penchez et prenez l'animal dans vos bras.")
    time.sleep(2)
    print("« Il a dû avoir faim et s'est retrouvé coincé dans la forêt. »")
    time.sleep(2)
    print("L'animal était recouvert de bandage sur le ventre.")
    time.sleep(2)
    print("« C'est vous qui l'aviez soigné ? » Demandez-vous.")
    time.sleep(2)
    print("La jeune fille hocha la tête.")
    time.sleep(2)
    print("« Cependant mes compétences en matière de concoction de potion ne sont pas incroyable, il faudrait l'emmener voir ma grand-mère. » Répondit la jeune fille avec inquiétude.")
    time.sleep(2)
    print("Vous serrez l'animal contre votre torse et vous vous levez.")
    time.sleep(2)
    print("« Je vous suis. »")
    time.sleep(2)
    print("La jeune fille vous sourit et vous commencez à marcher.")
    time.sleep(2)
    print("Sur le chemin, la jeune fille vous raconte l'histoire de son village.")
    time.sleep(2)
    print("« Il est dit que le village a été fondé par une vieille dame qui vivait près d'un lac et que chaque jour, elle allait arroser un arbre aux feuilles rouges. »")
    time.sleep(2)
    print("Un jour, elle a disparu et l'arbre a commencé à se dessécher.")
    time.sleep(2)
    print("« Les villageois ont alors décidé de prendre soin de l'arbre et de le protéger. »")
    time.sleep(2)
    print("« Mais qu'importe à quel point les villageois donnaient de l'eau ou d'amour, l'arbre ne reprenait pas vie. »")
    time.sleep(2)
    print("Le visage de la jeune fille s'assombrit.")
    time.sleep(2)
    print("« Ma mère aimait beaucoup cette histoire, elle disait que l'arbre était le symbole de notre village. »")
    time.sleep(2)
    print("« Mais un jour, elle est tombée malade et elle est morte et même temps que l'arbre. Ma grand-mère m'a dit que l'arbre était parti pour prendre soin d'elle... » Dit-elle en souriant.")
    time.sleep(2)
    print("Vous arrivez dans le village, les habitants vous regardent avec curiosité et méfiance.")
    time.sleep(2)
    print("Un viel homme s'apporche de vous, il possède une longue barbe marron et à regard sévère.")
    time.sleep(2)
    print("Le chien se met à grogner.")
    time.sleep(2)
    print("« Qui êtes-vous ? » Demande l'homme.")
    time.sleep(2)
    print("La jeune fille se met devant vous.")
    time.sleep(2)
    print("« C'est moi qui l'ait amener ici, grand-père. »")
    time.sleep(2)
    print("L'homme vous regarde avec méfiance.")
    time.sleep(2)
    print("« Comment vous vous appelez ? »")
    time.sleep(2)
    print("Il eut un moment de silence.")
    time.sleep(2)
    print("« Je m'appelle... »")
    time.sleep(2)
    print("Vous ne semblez pas vous souvenir de votre nom.")
    time.sleep(2)
    print("« Je... je ne sais pas. »")
    time.sleep(2)
    print("L'homme vous regarde avec surprise. Sa méfiance s'intensifie.")
    time.sleep(2)
    print("« Vous ne savez pas qui vous êtes ? » Demande l'homme.")
    time.sleep(2)
    print("Vous secouez la tête.")
    time.sleep(2)
    print("« Je l'ai trouvé évanoui dans la montagne. » Répondit la jeune fille.")
    time.sleep(2)
    print("L'homme regarde la jeune fille et soupira.")
    time.sleep(2)
    print("« Valecia, tu ne peux pas ramener toutes les personnes que tu trouves. »")
    time.sleep(2)
    print("La jeune fille, Valecia, baisse la tête.")
    time.sleep(2)
    print("« Je sais, grand-père, mais le chiene st blessé... »")
    time.sleep(2)
    print("L'homme soupire et vous regarde.")
    time.sleep(2)
    print("« Vous avez de la chance que Valecia vous ait trouvé. »")
    time.sleep(2)
    print("Il se tourne vers la jeune fille.")
    time.sleep(2)
    print("« Emmène-le voir la guérisseuse. »")
    time.sleep(2)
    print("Valecia hocha la tête et vous emmène dans une petite maison.")
    time.sleep(2)
    print("La guérisseuse était une vieille femme aux cheveux blancs, elle bougea pas même quand vous entrez dans la maison.")
    time.sleep(2)
    print("Valecia pose le chien sur une table.")
    time.sleep(2)
    print("« Il a besoin de soins. » Dit-elle.")
    time.sleep(2)
    print("La guérisseuse regarde l'animal et hoche la tête.")
    time.sleep(2)
    print("Elle mit sa main sur le corps de l'animal et murmura quelques mots.")
    time.sleep(2)
    print("Vous regardez la scène, impressionné.")
    time.sleep(2)
    print("La guérisseuse se tourne vers vous.")
    time.sleep(2)
    print("« Comment vous vous appelez ? »")
    time.sleep(2)
    