import time
import sys
sys.path.append('..mise_en_place')

def reveDuPasse():
    print("La voix vous revient en mémoire.")
    time.sleep(2)
    print("Un fond blanc vous aveugle, mais vous sentez une présence à vos côtés.")
    time.sleep(2)
    print("Vous vous sentez apaisé, en sécurité.")
    time.sleep(2)
    print("Vous essayez de vous tournez vers cette présence, mais la seule chose que vous remarquez sont son sourire et une longue chevelure blondes.")
    time.sleep(2)
    print("Une voix vous réveille.")
    time.sleep(2)
    print("Hoo ! Hey ! Vous allez bien ?")
    time.sleep(2)
    print("Vous ouvrez les yeux et une jeune fille vous regarde avec inquiétude.")
    time.sleep(2)
    print("Vous vous redressez, mais vous vous sentez faible.")
    time.sleep(2)
    print("« Vous dormiez depuis ce matin. » Dit la jeune fille.")
    time.sleep(2)
    print("Vous vous frottez les yeux et regardez autour de vous. Le soleil est déjà couché.")
    time.sleep(2)
    print("Quelque chose tremblote à vos côtés.")
    time.sleep(2)
    print("« Il va bien, mais il a besoin de repos. » Répondit la jeune fille en voyant votre regard.")
    time.sleep(2)
    print("Vous vous penchez et prenez l'animal dans vos bras.")
    time.sleep(2)
    print("« Il a dû avoir faim et s'est retrouvé coincé dans la forêt. »")
    time.sleep(2)
    print("L'animal était recouvert de bandage sur le ventre.")
    time.sleep(2)
    print("« C'est vous qui l'aviez soigné ? » Demandez-vous.")
    time.sleep(2)
    print("La jeune fille hocha la tête.")
    time.sleep(2)
    print("« Cependant mes compétences en matière de concoction de potion ne sont pas incroyable, il faudrait l'emmener voir ma mamie. » Répondit la jeune fille avec inquiétude.")
    time.sleep(2)
    print("Vous serrez l'animal contre votre torse et vous vous levez.")
    time.sleep(2)
    print("« Je vous suis. »")
    time.sleep(2)
    print("La jeune fille vous sourit et vous commencez à marcher.")
    time.sleep(2)
    print("Sur le chemin, la jeune fille vous raconte l'histoire de son village.")
    time.sleep(2)
    print("Il est dit que le village a été fondé par une vieille dame qui vivait près d'un lac et que chaque jour, elle allait arroser un arbre aux feuilles rouges.")
    time.sleep(2)
    print("Un jour, elle a disparu et l'arbre a commencé à se dessécher.")
    time.sleep(2)
    print("Les villageois ont alors décidé de prendre soin de l'arbre et de le protéger.")
    time.sleep(2)
    print("Mais qu'importe à quel point les villageois donnaient de l'eau ou d'amour, l'arbre ne reprenait pas vie.")
    time.sleep(2)
    