import time
import sys
import reveDuPasse from revedupasse

def unSouvenirEloigne(player):
    print("Vous vous réveillez dans une forêt sombre et dense.")
    time.sleep(2)
    print("Vous ne savez pas comment vous êtes arrivé ici.")
    time.sleep(2)
    print("Vous vous levez et regardez autour de vous.")
    time.sleep(2)
    print("Vous voyez un chemin devant vous.")
    time.sleep(2)
    print("Que faites-vous?")
    print("1. Suivre le chemin")
    print("2. Retourner d'où vous venez")
    choice = input("Votre choix: ")
    if choice == "1":
        print("Vous décidez de suivre le chemin.")
        time.sleep(2)
        print("Vous marchez pendant un moment.")
        time.sleep(2)
        print("Vous arrivez à un croisement.")
        time.sleep(2)
        print("Que faites-vous?")
        print("1. Aller à gauche")
        print("2. Aller à droite")
        choice = input("Votre choix: ")
        if choice == "1":
            print("Vous décidez d'aller à gauche.")
            time.sleep(2)
            print("Vous marchez pendant un moment.")
            time.sleep(2)
            print("Vous arrivez à une clairière.")
            time.sleep(2)
            print("Vous voyez une maison au loin.")
            time.sleep(2)
            print("Que faites-vous?")
            print("1. Aller à la maison")
            print("2. Prendre le chemin à droite")
            choice = input("Votre choix: ")
            if choice == "1":
                print("Vous décidez d'aller à la maison.")
                time.sleep(2)
                print("Vous arrivez à la maison.")
                time.sleep(2)
                print("Que faites-vous?")
                print("1. Entrer dans la maison")
                print("2. Examiner la maison")
                choice = input("Votre choix: ")
                if choice == "1":
                    print("Vous entrez dans la maison.")
                    time.sleep(2)
                    print("Vous voyez une vieille femme assise près du feu.")
                    time.sleep(2)
                    print("Que faite-vous?")
                    print("1. Parler à la vieille femme")
                    print("2. Rester silencieux")
                    choice = input("Votre choix: ")
                    if choice == "1":
                        print("Vous parlez à la vieille femme.")
                        time.sleep(2)
                        print("Elle vous dit qu'elle a besoin d'aide pour retrouver son chien.")
                        time.sleep(2)
                        print("Acceptez-vous de l'aider?")
                        print("1. Oui")
                        print("2. Non")
                        choice = input("Votre choix: ")
                        if choice == "1":
                            print("Vous acceptez d'aider la vieille femme.")
                            time.sleep(2)
                            print("Elle vous dit que son chien est dans la forêt près d'un arbre où des feuilles rouge.")
                            time.sleep(2)
                            print("Vous partez à la recherche du chien.")
                            time.sleep(2)
                            print("Vous suivez les directifs de la femme.")
                            time.sleep(2)
                            print("Vous vous trouvez rapidement devant l'arbre en question.")
                            time.sleep(2)
                            print("Une étrange sentiment de déjà vu vous envahit.")
                            time.sleep(2)
                            print("Vous avez le souffle couper.")
                            time.sleep(2)
                            print("Une voix à peine audible vous murmure:")
                            time.sleep(2)
                            print("« Que le monde m'oublie »")
                            time.sleep(2)
                            print("Une douleur vive vous envahit.")
                            time.sleep(2)
                            print("Vous vous retrouver dans une autre dimension.")
                            time.sleep(2)
                            print("Une lumière aveuglante se trouve devant vous.")
                            time.sleep(2)
                            print("Malgré tout elle est apaisante.")
                            time.sleep(2)
                            print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                            time.sleep(2)
                            print("Un couinement vous sort de votre torpeur.")
                            time.sleep(2)
                            print("Vous voyez le chien de la vieille femme.")
                            time.sleep(2)
                            print("Vous le prenez dans vos bras.")
                            time.sleep(2)
                            print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
                            time.sleep(2)
                            print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
                            time.sleep(2)
                            print("Vous retournez à la maison de la vieille femme.")
                            time.sleep(2)
                            print("La maison a disparu.")
                            time.sleep(2)
                            print('Une pluie fine commence à tomber.')
                            time.sleep(2)
                            print("Vous vous réfugiez dans une grotte non loin.")
                            time.sleep(2)
                            print("Le chien dans votre bras se met à couiner.")
                            time.sleep(2)
                            print("Vous le regardez.")
                            time.sleep(2)
                            print("Il vous regarde.")
                            time.sleep(2)
                            print("« Toi aussi tu es seul ? »")
                            time.sleep(2)
                            print("Le chien se colle à vous.")
                            time.sleep(2)
                            print("« On est deux maintenant. »")
                            time.sleep(2)
                            print("Vous vous endormez.")
                            reveDuPasse(player)
                        elif choice == "2":
                            print("Vous décidez de ne pas aider la vieille femme.")
                            time.sleep(2)
                            print("Vous sortez de la maison.")
                            time.sleep(2)
                            print("Un chien vous observe au loin.")
                            time.sleep(2)
                            print("Vous comprenez que c'est le chien de la vieille femme.")
                            time.sleep(2)
                            print("Vous essayez de l'attraper, mais il s'enfuit.")
                            time.sleep(2)
                            print("En le poursuivant, vous vous retrouvez devant un arbre avec des feuilles rouges.")
                            time.sleep(2)
                            print("Une étrange sentiment de déjà vu vous envahit.")
                            time.sleep(2)
                            print("Vous avez le souffle couper.")
                            time.sleep(2)
                            print("Une voix à peine audible vous murmure:")
                            time.sleep(2)
                            print("« Que le monde m'oublie »")
                            time.sleep(2)
                            print("Une douleur vive vous envahit.")
                            time.sleep(2)
                            print("Vous vous retrouver dans une autre dimension.")
                            time.sleep(2)
                            print("Une lumière aveuglante se trouve devant vous.")
                            time.sleep(2)
                            print("Malgré tout elle est apaisante.")
                            time.sleep(2)
                            print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                            time.sleep(2)
                            print("Un couinement vous sort de votre torpeur.")
                            time.sleep(2)
                            print("Vous voyez le chien de la vieille femme.")
                            time.sleep(2)
                            print("Vous le prenez dans vos bras.")
                            time.sleep(2)
                            print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
                            time.sleep(2)
                            print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
                            time.sleep(2)
                            print("Vous retournez à la maison de la vieille femme.")
                            time.sleep(2)
                            print("La maison a disparu.")
                            time.sleep(2)
                            print('Une pluie fine commence à tomber.')
                            time.sleep(2)
                            print("Vous vous réfugiez dans une grotte non loin.")
                            time.sleep(2)
                            print("Le chien dans votre bras se met à couiner.")
                            time.sleep(2)
                            print("Vous le regardez.")
                            time.sleep(2)
                            print("Il vous regarde.")
                            time.sleep(2)
                            print("« Toi aussi tu es seul ? »")
                            time.sleep(2)
                            print("Le chien se colle à vous.")
                            time.sleep(2)
                            print("« On est deux maintenant. »")
                            time.sleep(2)
                            print("Vous vous endormez.")
                        reveDuPasse(player)
                    elif choice == "2":
                        print("Vous restez silencieux.")
                        time.sleep(2)
                        print("Vous regarder à l'intérieur de la maison.")
                        time.sleep(2)
                        print("Un sentiment de malaise vous envahit.")
                        time.sleep(2)
                        print("Vous ressortez de la maison.")  
                        time.sleep(2)
                        print("Un chien vous observe au loin.")
                        time.sleep(2)
                        print("Vous avez l'impression qu'il vous appelle.")
                        time.sleep(2)
                        print("Vous décidez de le suivre.")
                        time.sleep(2)
                        print("En le poursuivant, vous vous retrouvez devant un arbre avec des feuilles rouges.")
                        time.sleep(2)
                        print("Une étrange sentiment de déjà vu vous envahit.")
                        time.sleep(2)
                        print("Vous avez le souffle couper.")
                        time.sleep(2)
                        print("Une voix à peine audible vous murmure:")
                        time.sleep(2)
                        print("« Que le monde m'oublie »")
                        time.sleep(2)
                        print("Une douleur vive vous envahit.")
                        time.sleep(2)
                        print("Vous vous retrouver dans une autre dimension.")
                        time.sleep(2)
                        print("Une lumière aveuglante se trouve devant vous.")
                        time.sleep(2)
                        print("Malgré tout elle est apaisante.")
                        time.sleep(2)
                        print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                        time.sleep(2)
                        print("Un couinement vous sort de votre torpeur.")
                        time.sleep(2)
                        print("Le chien vous regarde en remuant la queue.")
                        time.sleep(2)
                        print("Vous le prenez dans vos bras.")
                        time.sleep(2)
                        print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
                        time.sleep(2)
                        print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
                        time.sleep(2)
                        print("Vous retournez à la maison de la vieille femme.")
                        time.sleep(2)
                        print("La maison a disparu.")
                        time.sleep(2)
                        print('Une pluie fine commence à tomber.')
                        time.sleep(2)
                        print("Vous vous réfugiez dans une grotte non loin.")
                        time.sleep(2)
                        print("Le chien dans votre bras se met à couiner.")
                        time.sleep(2)
                        print("Vous le regardez.")
                        time.sleep(2)
                        print("Il vous regarde.")
                        time.sleep(2)
                        print("« Toi aussi tu es seul ? »")
                        time.sleep(2)
                        print("Le chien se colle à vous.")
                        time.sleep(2)
                        print("« On est deux maintenant. »")
                        time.sleep(2)
                        print("Vous vous endormez.")
                        reveDuPasse(player)
                elif choice == "2":
                    print("Vous décidez d'examiner la maison.")
                    time.sleep(2)
                    print("Vous ne trouvez rien d'intéressant.")
                    time.sleep(2)
                    print("Vous vous retournez.")
                    time.sleep(2)
                    print("Un chien vous observe au loin.")
                    time.sleep(2)
                    print("Vous avez l'impression qu'il vous appelle.")
                    time.sleep(2)
                    print("Vous décidez de le suivre.")
                    time.sleep(2)
                    print("En le poursuivant, vous vous retrouvez devant un arbre avec des feuilles rouges.")
                    time.sleep(2)
                    print("Une étrange sentiment de déjà vu vous envahit.")
                    time.sleep(2)
                    print("Vous avez le souffle couper.")
                    time.sleep(2)
                    print("Une voix à peine audible vous murmure:")
                    time.sleep(2)
                    print("« Que le monde m'oublie »")
                    time.sleep(2)
                    print("Une douleur vive vous envahit.")
                    time.sleep(2)
                    print("Vous vous retrouver dans une autre dimension.")
                    time.sleep(2)
                    print("Une lumière aveuglante se trouve devant vous.")
                    time.sleep(2)
                    print("Malgré tout elle est apaisante.")
                    time.sleep(2)
                    print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                    time.sleep(2)
                    print("Un couinement vous sort de votre torpeur.")
                    time.sleep(2)
                    print("Le chien vous regarde en remuant la queue.")
                    time.sleep(2)
                    print("Vous le prenez dans vos bras.")
                    time.sleep(2)
                    print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
                    time.sleep(2)
                    print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
                    time.sleep(2)
                    print("Vous retournez à la maison de la vieille femme.")
                    time.sleep(2)
                    print("La maison a disparu.")
                    time.sleep(2)
                    print('Une pluie fine commence à tomber.')
                    time.sleep(2)
                    print("Vous vous réfugiez dans une grotte non loin.")
                    time.sleep(2)
                    print("Le chien dans votre bras se met à couiner.")
                    time.sleep(2)
                    print("Vous le regardez.")
                    time.sleep(2)
                    print("Il vous regarde.")
                    time.sleep(2)
                    print("« Toi aussi tu es seul ? »")
                    time.sleep(2)
                    print("Le chien se colle à vous.")
                    time.sleep(2)
                    print("« On est deux maintenant. »")
                    time.sleep(2)
                    print("Vous vous endormez.")
                    reveDuPasse(player)
            elif choice == "2":
                print("Vous décidez de prendre le chemin à droite.")
                time.sleep(2)
                print("Vous marchez pendant un moment.")
                time.sleep(2)
                print("Vous arrivez à un lac.")
                time.sleep(2)
                print("Vous voyez un bateau au loin.")
                time.sleep(2)
                print("Que faites-vous?")
                print("1. Aller au bateau")
                print("2. Rester au bord du lac")
                choice = input("Votre choix: ")
                if choice == "1":
                    print("Vous décidez d'aller au bateau.")
                    time.sleep(2)
                    print("Vous arrivez au bateau.")
                    time.sleep(2)
                    print("Vous montez à bord.")
                    time.sleep(2)
                    print("Le bateau se met à bouger tout seul.")
                    time.sleep(2)
                    print("Vous n'avez pas le contrôle.")
                    time.sleep(2)
                    print("Le bateau vous emmène vers le centre du lac.")
                    time.sleep(2)
                    print("Vous voyez une lumière éblouissante au fond du lac.")
                    time.sleep(2)
                    print("Vous vous sentez attiré par cette lumière.")
                    time.sleep(2)
                    print("Vous plongez dans le lac.")
                    time.sleep(2)
                    print("Vous vous retrouvez dans une autre dimension.")
                    time.sleep(2)
                    print("Une lumière aveuglante se trouve devant vous.")
                    time.sleep(2)
                    print("Malgré tout elle est apaisante.")
                    time.sleep(2)
                    print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                    time.sleep(2)
                    print("Un couinement vous sort de votre torpeur.")
                    time.sleep(2)
                    print("Vous vous retrouvez sur le bord du lac.")
                    time.sleep(2)
                    print("Un chien vous regarde en couinant.")
                    time.sleep(2)
                    print("Vous vous relevez.")
                    time.sleep(2)
                    print("Vous avez un sentiment de tristesse qui vous envahit.")
                    time.sleep(2)
                    print("Le chien se colle à vous.")
                    time.sleep(2)
                    print("Une pluie fine commence à tomber.")
                    time.sleep(2)
                    print("Vous vous réfugiez dans une grotte non loin.")
                    time.sleep(2)
                    print("Pour une quelconque raison, le chien vous suit.")
                    time.sleep(2)
                    print("Vous fermez les yeux.")
                    time.sleep(2)
                    print("Le chien se colle à vous")
                    time.sleep(2)
                    print("« On est deux maintenant. »")
                    time.sleep(2)
                    print("Vous vous endormez.")
                    reveDuPasse(player)
                elif choice == "2":
                    print("Vous décidez de rester au bord du lac.")
                    time.sleep(2)
                    print("Vous vous asseyez et contemplez le lac.")
                    time.sleep(2)
                    print("Une brume épaisse commence à se lever.")
                    time.sleep(2)
                    print("Vous entendez un bruit derrière vous.")
                    time.sleep(2)
                    print("Vous vous retournez.")
                    time.sleep(2)
                    print("Un chien vous observe.")
                    time.sleep(2)
                    print("Vous avez l'impression qu'il vous appelle.")
                    time.sleep(2)
                    print("Vous décidez de le suivre.")
                    time.sleep(2)
                    print("En le poursuivant, vous vous retrouvez devant un arbre avec des feuilles rouges.")
                    time.sleep(2)
                    print("Une étrange sentiment de déjà vu vous envahit.")
                    time.sleep(2)
                    print("Vous avez le souffle couper.")
                    time.sleep(2)
                    print("Une voix à peine audible vous murmure:")
                    time.sleep(2)
                    print("« Que le monde m'oublie »")
                    time.sleep(2)
                    print("Une douleur vive vous envahit.")
                    time.sleep(2)
                    print("Vous vous retrouver dans une autre dimension.")
                    time.sleep(2)
                    print("Une lumière aveuglante se trouve devant vous.")
                    time.sleep(2)
                    print("Malgré tout elle est apaisante.")
                    time.sleep(2)
                    print(f"{player.name}, je t'attends. À la tour de l'oubli.")
                    time.sleep(2)
                    print("Un couinement vous sort de votre torpeur.")
                    time.sleep(2)
                    print("Le chien vous regarde en remuant la queue.")
                    time.sleep(2)
                    print("Vous le prenez dans vos bras.")
                    time.sleep(2)
                    print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
                    time.sleep(2)
                    print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
                    time.sleep(2)
                    print("Une pluie fine commence à tomber.")
                    time.sleep(2)
                    print("Vous vous réfugiez dans une grotte non loin.")
                    time.sleep(2)
                    print("Le chien dans votre bras se met à couiner.")
                    time.sleep(2)
                    print("Vous le regardez.")
                    time.sleep(2)
                    print("Il vous regarde.")
                    time.sleep(2)
                    print("« Toi aussi tu es seul ? »")
                    time.sleep(2)
                    print("Le chien se colle à vous.")
                    time.sleep(2)
                    print("« On est deux maintenant. »")
                    time.sleep(2)
                    print("Vous vous endormez.")
                    reveDuPasse(player)      
    elif choice == "2":
        print("Vous décidez de retourner d'où vous venez.")
        time.sleep(2)
        print("Vous marchez pendant un moment.")
        time.sleep(2)
        print("Vous marchez pendant un moment.")
        time.sleep(2)
        print("Vous arrivez à une clairière.")
        time.sleep(2)
        print('Vous voyez un arbre avec des feuilles rouges.')
        time.sleep(2)
        print("Une étrange sentiment de déjà vu vous envahit.")
        time.sleep(2)
        print("Vous avez le souffle couper.")
        time.sleep(2)
        print("Une voix à peine audible vous murmure:")
        time.sleep(2)
        print("« Que le monde m'oublie »")
        time.sleep(2)
        print("Une douleur vive vous envahit.")
        time.sleep(2)
        print("Vous vous retrouver dans une autre dimension.")
        time.sleep(2)
        print("Une lumière aveuglante se trouve devant vous.")
        time.sleep(2)
        print("Malgré tout elle est apaisante.")
        time.sleep(2)
        print(f"{player.name}, je t'attends. À la tour de l'oubli.")
        time.sleep(2)
        print("Un couinement vous sort de votre torpeur.")
        time.sleep(2)
        print("Un chien vous regarde en remuant la queue.")
        time.sleep(2)
        print("Vous le prenez dans vos bras.")
        time.sleep(2)
        print("Avant de quitter l'endroit où se trouve l'arbre rouge, vous vous retournez une dernière fois.")
        time.sleep(2)
        print("Pour une quelconque raison, vous avez l'impression que vous ne reverrez jamais cet endroit.")
        time.sleep(2)
        print("Une pluie fine commence à tomber.")
        time.sleep(2)
        print("Vous vous réfugiez dans une grotte non loin.")
        time.sleep(2)
        print("Le chien dans votre bras se met à couiner.")
        time.sleep(2)
        print("Vous le regardez.")
        time.sleep(2)
        print("Il vous regarde.")
        time.sleep(2)
        print("« Toi aussi tu es seul ? »")
        time.sleep(2)
        print("Le chien se colle à vous.")
        time.sleep(2)
        print("« On est deux maintenant. »")
        time.sleep(2)
        print("Vous vous endormez.")
        reveDuPasse(player)